Add error handling to cache purge.

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -34,10 +34,19 @@ jobs:
 
       - name: Purge Cloudflare cache
         run: |
-          curl https://api.cloudflare.com/client/v4/zones/$ZONE_ID/purge_cache \
-          -H 'Content-Type: application/json' \
-          -H 'Authorization: Bearer $CLOUDFLARE_API_TOKEN' \
-          -d '{"hosts": ["twotech.twohoursonelife.com"]}'
+          response=$(
+            curl https://api.cloudflare.com/client/v4/zones/$ZONE_ID/purge_cache \
+              -H "Content-Type: application/json" \
+              -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
+              -d '{"hosts": ["twotech.twohoursonelife.com"]}'
+          )
+
+          echo "$response"
+
+          if echo "$response" | grep -q '"success":false'; then
+            echo "Error: Cloudflare API failed." >&2
+            exit 1
+          fi
         env:
           CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
-          ZONE_ID: ${{ vars.CLOUDFLARE_API_TOKEN }}
+          ZONE_ID: ${{ vars.ZONE_ID }}
